name: Build & Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login & Build & Push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: docker.io/hardik0811/mern-app:latest
          cache-from: type=registry,ref=docker.io/hardik0811/mern-app:latest
          cache-to: type=inline
