name: Build & Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      
      
      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD  }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      
      - name: Build Docker Image
        run: docker build -t docker.io/hardik0811/mern-app:latest .

      - name: Push Docker Image
        run: docker push docker.io/hardik0811/mern-app:latest
