name: Build & Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: hardik0811
          password: barbaria888
          registry: docker.io   
          logout: true          
        
      
      - name: Build Docker Image
        run: docker build -t docker.io/hardik0811/mern-app:latest .

      - name: Push Docker Image
        run: docker push docker.io/hardik0811/mern-app:latest
