name: ci-pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Backend Dependencies
        run: |
          cd server
          npm install

      - name: Run Backend Tests
        run: |
          cd server
          npm test

      - name: Install Frontend Dependencies
        run: |
          cd client
          npm install

      - name: Run Frontend Tests
        run: |
          cd client
          npm test